version: "3.3"

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: development
        CLEAR_BUILD_DEPENDENCIES: 'false'
    environment:
      - NODE_ENV=development
    networks:
      - default
    ports:
      - "4000:4000"
    command: "yarn watch"
    volumes:
      - ".:/code"
      - "/code/node_modules"

networks:
  default: {}
