version: "3.4"

services:
  app:
    build:
      context: .
      target: build
    environment:
      - NODE_ENV=development
      - NODE_CONFIG_ENV=development
      - >
        NODE_CONFIG={
          "kafka": {
            "broker": "kafka:9092"
          },
          "sequelize": { "host": "postgres" },
          "redis": { "host": "redis" }
        }
    networks:
      - default
    ports:
      - "4000:4000"
    command: "yarn watch:cmd ts-node --files --inspect=9000 src/index.ts"
    volumes:
      - ".:/code"
      - "/code/node_modules"
networks:
  default: {}
