apiVersion: v1
kind: Service
metadata:
  name: <%= microserviceName %>-service
spec:
  type: NodePort
  selector:
    app: <%= microserviceName %>
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
